SELECT * FROM public.customer_behavior

--Q1. "In which season do customers spend the most on average,
--and what is the most popular payment method used during that specific peak season?"
SELECT season, 
       payment_method, 
       COUNT(customer_id) AS transaction_count
FROM customer_behavior
WHERE season = (
    SELECT season 
    FROM customer_behavior 
    GROUP BY season 
    ORDER BY AVG(purchase_amount) DESC 
    LIMIT 1
)
GROUP BY season, payment_method
ORDER BY transaction_count DESC;

-- Q2. Which product categories show the highest 'spending volatility' between seasons?
WITH customer_seasonal AS (
    SELECT 
        category, 
        season, 
        AVG(purchase_amount) AS seasonal_avg
    FROM customer_behavior
    GROUP BY category, season
)
SELECT 
    category,
    AVG(seasonal_avg) AS yearly_avg_spend,
    (MAX(seasonal_avg) - MIN(seasonal_avg)) AS seasonal_range,
    ((MAX(seasonal_avg) - MIN(seasonal_avg)) / AVG(seasonal_avg)) AS volatility_index
FROM customer_seasonal
GROUP BY category
ORDER BY volatility_index DESC;

-- Q3. Total revenue generated by male vs. female customers
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer_behavior
GROUP BY gender;

-- Q4. Customers who used a discount but still spent more than the average
SELECT customer_id, purchase_amount
FROM customer_behavior
WHERE discount_applied = 'Yes' 
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_behavior);

-- Q5. Top 5 products with the highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating::numeric), 2) AS "Average Product Rating"
FROM customer_behavior
GROUP BY item_purchased
ORDER BY "Average Product Rating" DESC
LIMIT 5;

-- Q6. Average Purchase Amounts between Standard and Express Shipping
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS avg_spend
FROM customer_behavior
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q7. Subscription Impact: Compare average spend and total revenue
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_behavior
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Q8. Top 5 products with the highest percentage of discounted purchases
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q9. Customer Segmentation (New, Returning, Loyal)
WITH customer_type AS (
    SELECT customer_id, previous_purchases,
    CASE WHEN previous_purchases = 1 THEN 'New'
         WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
         ELSE 'Loyal'
    END AS customer_segment
    FROM customer_behavior
)
SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

-- Q10. Top 3 most purchased products within each category
WITH item_counts AS (
    SELECT category, item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_behavior
    GROUP BY category, item_purchased
)
SELECT category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q11. Relationship between repeat buyers (>5 purchases) and subscriptions
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q12. Revenue contribution of each age group
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;